mysite/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from mysite import views

#url和view.py中的函数进行关联
urlpatterns = patterns('',
                    url(r'^$', views.polls, name='index'),
                    url(r'^init$', views.init, name='init'),
                    url(r'^login$', views.login, name='login'),
                    url(r'^loginpwd$', views.loginpwd, name='loginpwd'),
                    url(r'^clearlogincookies$', views.clearlogincookies, name='clearlogincookies'),
                    #url(r'valid/(?P<key>[^/]+)/(?P<uid>\d+)$',views.valid,name='valid'),
                    url(r'^reg$', views.reg, name='reg'),
                    url(r'^picreg$', views.picreg, name='picreg'),
                    url(r'^regexl$', views.regexl, name='regexl'),
                    url(r'^admin$', views.admin, name='admin'),
                    url(r'^createpoll$', views.createpoll, name='createpoll'),
                    url(r'^addcandidate$', views.addcandidate, name='addcandidate'),
                    url(r'^candidate/(?P<id>[0-9]+)$', views.candidate, name='candidate'),
                    url(r'^candidates$', views.candidates, name='candidates'),
                    url(r'^pollvote$', views.pollvote, name='pollvote'),
                    #url(r'editcandidates$',views.editcandidates, name='editcandidates'),
                    url(r'^getauthkey$', views.getauthkey, name='getauthkey'),
                    url(r'^gopagevoters$', views.gopagevoters, name='gopagevoters'),
                    url(r'^getseed$', views.getseed, name='getseed'),
                    url(r'^bind/(?P<seed>[^/]+)$', views.bind, name='bind'),
                    url(r'^auth/(?P<key>[0-9]+)/(?P<value>[^/]+)$', views.auth, name='auth'),
                    url(r'^voters/(?P<page>[0-9]+)$', views.voters, name='voters'),
                    url(r'^voters$', views.voters, name='voters'),
                    url(r'^qryvoters/(?P<page>[0-9]+)$', views.qryvoters, name='qryvoters'),
                    url(r'^qryvoters$', views.qryvoters, name='qryvoters'),
                    url(r'^qrycandidates$', views.qrycandidates, name='qrycandidates'),
                    url(r'^qrycandidates/(?P<page>[0-9]+)$', views.qrycandidates, name='qrycandidates'),
                    url(r'^delvoter/(?P<id>[0-9]+)$', views.delvoter, name='delvoter'),
                    url(r'^delcandidate/(?P<id>[0-9]+)$', views.delcandidate, name='delcandidate'),
                    url(r'^poll/(?P<topicid>[0-9]+)$', views.poll, name='poll'),
                    url(r'^pollresult/(?P<topicid>[0-9]+)$', views.pollresult, name='pollresult'),
                    url(r'^pollresult/(?P<topicid>[0-9]+)/(?P<type>[0-9]+)$', views.pollresult, name='pollresult'),
                    url(r'^polls/(?P<type>[^/]+)(/(?P<key>[^/]+)/(?P<uid>\d+))?$', views.polls, name='polls'),
                    url(r'^pollvote/(?P<topicid>[^/]+)/(?P<optid>[^/]+)$', views.pollvote, name='pollvote'),
                    url(r'^gettext/(?P<id>[0-9]+)$', views.gettext, name='gettext'),
                    url(r'^settext/(?P<id>[0-9]+)$', views.settext, name='settext'),
                    url(r'^judge$', views.judge, name='judge'),
                       )

poll/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'partdetect.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('mysite.urls',namespace='mysite')),
) + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/views.py
# -*- coding: utf-8 -*-
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import  render_to_response
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import RequestContext
from mysite.forms import LoginForm, RegForm, RegExlForm, LoginpwdForm, RegCanditeForm, SetTextForm, RegByJudgeForm
from mysite.models import User, Pic, Question, User_Choice_Rel, User_Choice2_Rel, User_Question, Valid, Choice, \
    Choice2, Candidate, Var, Log, Exl, Text, Judge_Queue
from django.db.models import Q
import md5,string,xlrd,os,random
import re
from datetime import datetime
from django.utils import timezone
DEBUG = True
import logging
logging.basicConfig(format='%(asctime)s %(message)s', filename='operator.log', level=logging.INFO)

def getGloVar(key):
    return Var.objects.all().filter(name = key)[0].val

def setGloVar(key, val):
    obj = Var.objects.all().filter(name = key)[0]
    obj.val = val
    obj.save()

def crypt(key):
    m1 = md5.new()
    m1.update(key[0 : len(key) - 1])
    m1.update(key[1 : len(key)])
    m1.update(key[1 : len(key) - 1])
    m1.update(m1.hexdigest())
    for i in range(len(key) - 1, 0 , -1):
        m1.update(key[i])
    m1.update(Var.objects.all().filter(name = "seed")[0].val)
    return m1.hexdigest()


def init(request):
    #删除数据库所有数据
    if DEBUG :
        Pic.objects.all().delete()
        User.objects.all().delete()
        Valid.objects.all().delete()
        Question.objects.all().delete()
        Var.objects.all().delete()
        Candidate.objects.all().delete()
        Exl.objects.all().delete()
        Log.objects.all().delete()
        Text.objects.all().delete()
    if DEBUG or Var.objects.all().filter("bind") == None:
        Var(name = "authkey", val = "10000").save()
        Var(name = "bind", val = "0").save()
        Var(name = "seed", val = ''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits) for _ in range(10))).save()
        Text(id = 0, content = "").save()
        Text(id = 1, content = "").save()
        Text(id = 2, content = "").save()
    return HttpResponse('OK!')

@csrf_exempt
def msg(request, backurl, msginf):
    c = {
        "backurl": backurl,
        "msginf": msginf,
    }
    return render_to_response('mysite/msg.html', c, context_instance=RequestContext(request))


# 加密性 和 安全性 有待增强
@csrf_exempt
def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST, request.FILES)
        if form.is_valid():
            tsn = request.FILES['docfile'].name
            uid = request.POST['idsn']
            newdoc = Pic(docfile = request.FILES['docfile'], uid = uid)
            newdoc.save()            
            request.FILES['docfile'].seek(0)
            m1 = md5.new()
            m1.update(request.FILES['docfile'].read())
            if len(User.objects.all().filter(idsn = uid)) >= 1 :
                valids = Valid.objects.all().filter(uid = uid)
                if len(valids) == 0 :
                    Valid(uid = uid, key = m1.hexdigest()).save()
                else:
                    valids[0].key = m1.hexdigest()
                    valids[0].save()
            return HttpResponse(m1.hexdigest() + "/" + uid)
    form = LoginForm()
    documents = Pic.objects.all()
    return render_to_response(
        'mysite/login.html',
        {'form': form, 'documents': documents},
        context_instance=RequestContext(request)
    )

def addVoter(name, idsn, phone, type = 0):
    chkobjs = User.objects.all().filter(idsn = idsn)
    if len(chkobjs) == 0:
        try:
            if isinstance(phone,(float,int)):
                User(idsn = idsn, username = name, phone = str(int(phone)), type = int(type), suffix=idsn[14:18]).save()
            else:
                User(idsn = idsn, username = name, phone = phone, type = int(type), suffix=idsn[14:18]).save()
        except:
            if isinstance(phone,(float,int)):
                User(idsn = idsn, username = name, phone = str(int(phone)), type = 0, suffix=idsn[14:18]).save()
            else:
                User(idsn = idsn, username = name, phone = phone, type = 0, suffix=idsn[14:18]).save()
    else:
        chkobjs[0].username = name
        if isinstance(phone,(float,int)):
            chkobjs[0].phone = str(int(phone))
        else:
            chkobjs[0].phone = phone
        chkobjs[0].suffix = idsn[14:18]
        try:
            chkobjs[0].type = int(type)
        except:
            chkobjs[0].type = 0
        chkobjs[0].save()


@csrf_exempt
def regexl(request):
    if chkAdminCookies(request) == None:
        return msg(request, "mysite:index", "无权限查看！")
    if request.method == 'POST':
        form = RegExlForm(request.POST, request.FILES)
        if form.is_valid():
            for obj in Exl.objects.all():
                os.remove(obj.docfile.path)
                obj.delete()
            newexl = Exl(docfile = request.FILES['docfile'])
            newexl.save()
            path = newexl.docfile.path
            workbook = xlrd.open_workbook(path)
            worksheet = workbook.sheet_by_index(0)
            #try:
            for i in range(1,worksheet.nrows):
                if worksheet.ncols == 3:
                    addVoter(worksheet.cell_value(i,0), worksheet.cell_value(i,1), worksheet.cell_value(i,2))
                elif worksheet.ncols == 4:
                    addVoter(worksheet.cell_value(i,0), worksheet.cell_value(i,1), worksheet.cell_value(i,2), worksheet.cell_value(i,3))
                else:
                    raise
            return msg(request, "mysite:regexl", "导入成功！")
            #except:
            #    return msg(request, "mysite:regexl", "导入异常！")
    form = RegExlForm()
    return render_to_response('mysite/regexl.html', {"form": form}, context_instance=RequestContext(request))


@csrf_exempt
def valid(request, key, uid, pwd = None):
    if (uid == None or uid == "") :
        return False
    if  ( (key == None or key == "") and (pwd == None or pwd == "")):
        return False
    if pwd != None and pwd != "":
        qryRes = User.objects.all().filter(idsn = uid).filter(pwd = pwd)
        if qryRes != None and len(qryRes) > 0:
            return True
        else:
            return False
    valids = Valid.objects.all().filter(uid = uid)
    if len(valids) >= 1:
        if valids[0].key == key:
            return True
    return False




@csrf_exempt
def reg(request):
    #注册用户
    #对应的网页模版地址为 mysite/templates/mysite/reg.html
    if chkAdminCookies(request) == None:
        return msg(request, "mysite:index", "无权限查看！")
    if request.method == 'POST':
        form = RegForm(request.POST)
        if form.is_valid():
            username = request.POST['username'].strip()
            idsn = request.POST['idsn'].strip()
            phone = request.POST['phone'].strip()
            type = int(request.POST['type'])
            qry_usrs = User.objects.all().filter(idsn = idsn)
            if len(qry_usrs) != 0:
                qry_usrs[0].username = username
                qry_usrs[0].phone = phone
                qry_usrs[0].save()
                msg(request, "mysite:reg", '用户已存在并重新修改！')
            newusr = User(username = username, idsn = idsn, phone = phone, type = type, suffix = idsn[14:18])
            newusr.save()
            return msg(request, "mysite:reg", "注册成功！")
        return msg(request, "mysite:reg", "关键项未填!")
    form = RegForm()
    usrs = User.objects.all()
    c = {
        'form': form,
        'usrs': usrs,
    }
    return render_to_response('mysite/reg.html', c, context_instance=RequestContext(request))

def chkAdminCookies(request):
    if DEBUG == True:
        return True
    #检查cookies是否合法
    key = request.session.get('authkey', None)
    value = request.session.get('authvalue', None)
    timeNow = timezone.now()
    pollsRunning = Question.objects.all().filter(st__lte = timeNow).filter(dt__gt = timeNow)
    if pollsRunning != None and len(pollsRunning) > 0:
        return None
    if key and value and int(key) == int(getGloVar("authkey")) - 1 and crypt(key) == value:
        return True
    else:
        return None

@csrf_exempt
def admin(request):
    if chkAdminCookies(request):
        logging.info("管理员 进入 管理页面")
        return manage(request)
    return render_to_response('mysite/adminlogin.html', context_instance=RequestContext(request))

@csrf_exempt
def manage(request):
    if chkAdminCookies(request):
        c = {
            'topics' : Question.objects.all()
        }
        return render_to_response('mysite/manage.html', c, context_instance=RequestContext(request))


@csrf_exempt
def createpoll(request):
    if request.method == 'POST':
        topic = request.POST['topic']
        i = 0
        st = None
        dt = None
        sdate_str = request.POST['sdate']
        tdate_str = request.POST['tdate']
        sdate_list = sdate_str.split('-')
        tdate_list = tdate_str.split('-')
        shour = int(request.POST['shour'])
        smin = int(request.POST['smin'])
        thour = int(request.POST['thour'])
        tmin = int(request.POST['tmin'])
        commitcnt = int(request.POST['commitcnt'])
        try:
            st = datetime(
                year = int( sdate_list[0]), month = int(sdate_list[1]), day = int(sdate_list[2]), hour = shour, minute = smin)
            dt = datetime(
                year = int( tdate_list[0]), month = int(tdate_list[1]), day = int(tdate_list[2]), hour = thour, minute = tmin)
        except:
            return msg(request, "mysite:createpoll", "非法日期")
        if len(Question.objects.all().filter(text = topic)) != 0:
            return msg(request, "mysite:createpoll", "不要创建标题重复的投票")
        question = Question(text = topic, st = st, dt = dt, commitcnt = commitcnt)
        question.save()
        while True:

mysite/templates/mysite/candidate.html
{% include 'mysite/header.html' %}
{% load static %}
<div class="container" xmlns="http://www.w3.org/1999/html">
    {% if obj %}
        <p>姓名：{{ obj.user.username }}</p>
        <p>头像：<img src="{{obj.picfile.url}}" width="70" height="100" alt="Some image"></p>
        <p>竞选类型：
            {% if obj.eletype == 0 %}
                委员
            {% else %}
                主任
            {% endif %}
        </p>
        <p>政治面貌：{{ obj.politics }}</p>
        <p>性别：{{ obj.sex }}</p>
        <p>出生年份：{{ obj.birthyear }}</p>
        <p>学历：{{ obj.backgroud }}</p>
        <p>民族：{{ obj.nation }}</p>
        {% if obj.eletype == 1 %}
            <p>竞选视频：{{ obj.videourl|safe }}</p>
        {% endif %}
        <p>其他说明：{{ obj.othertext }}</p>
    {% endif %}
     <p><a  class="btn btn-default" href="{% url "mysite:candidates" %}">返回</a></p>
</div>
<style type="text/css">
    #navcandidates {color:red;}
</style>

mysite/templates/mysite/candidates.html
{% include 'mysite/header.html' %}
{% load static %}
<div class="container">
    <p>村长候选人:</p>

    {% for candidate in candidates1 %}
        <div id="candidates" style="float:left;padding-left: 20pt">
            <a href="{% url "mysite:candidate" candidate.id %}">
                <img src="{% if candidate.picfile %}{{candidate.picfile.url}} {% endif %}" width="70" height="100" alt="Some image">
                <p>{{ candidate.user.username }}&nbsp;{{ candidate.user.suffix }}</p>
            </a>
        </div>
    {% endfor %}
</div>
<br> <br>
<div class="container">
    <p>委员候选人:</p>
    {% for candidate in candidates0 %}
        <div id="candidates" style="float:left;padding-left: 20pt">
            <a href="{% url "mysite:candidate" candidate.id %}">
                <img src="{% if candidate.picfile %}{{candidate.picfile.url}} {% endif %}" width="70" height="100" alt="Some image">
                <p>{{ candidate.user.username }}&nbsp;{{ candidate.user.suffix }}</p>
            </a>
        </div>
    {% endfor %}
</div>

<style type="text/css">
    #navcandidates {color:red;}
</style>

mysite/templates/mysite/gettext.html
{% include 'mysite/header.html' %}
{% load bootstrap %}
{% load static %}
{% load custom_filter %}

<div class="container">
    {% autoescape on %}
        {{ content|safe }}
    {% endautoescape %}

</div>


<style type="text/css">
    #{{ navlabel }} {color:red;}
</style>

mysite/templates/mysite/judge.html
{% include 'mysite/manage.html' %}
{% load static %}
{% load bootstrap %}


<div class="container">
    {% if obj %}
        <p>姓名：{{ obj.username }}</p>
        <p>手机号：{{ obj.phone }}</p>
        <p>身份证号：{{ obj.idsn }}</p>
        <p>选民类型：
            {% if obj.type == 0 %}
                当地居住选民
            {% elif obj.type == 1 %}
                外地居住选民
            {% else %}
                非本村户籍选民
            {% endif %}
        </p>
        <p>本人和身份证正面照：<img src="{{obj.frontpic.url}}" width="900"  alt="本人和身份证正面照"></p>
        <p>本人和身份证背面照：<img src="{{obj.backpic.url}}" width="900"  alt="本人和身份证背面照"></p>
        <form action="{% url 'mysite:judge' %}" method="post" align="center">
            <input type="hidden" name="id" value="{{ obj.id }}" />
            <button name="flag" type="submit" class="btn btn-danger" value="0">拒绝</button>
            <button name="flag" type="submit" class="btn btn-success" value="1">接受</button>
        </form>
    {% else %}
        当前没有审核任务！
    {% endif %}
</div>
<style type="text/css">
    #navjudge {color:red;}
</style>

mysite/templates/mysite/login.html
{% include 'mysite/header.html' %}
{% load bootstrap %}
{% load static %}
<div class="container">


    <div class="container">
        <!-- Upload form. Note enctype attribute! -->
        <form
                {% if picreg %}
                    action="{% url 'mysite:picreg' %}"
                {% else %}
                    action="{% url 'mysite:login' %}"
                {% endif %}
              method="post" enctype="multipart/form-data">

                {{form | bootstrap}}

            </p>

            <p><input class="btn btn-default" type="submit"
                        {% if picreg %}
                            value="提交登记申请"
                        {% else %}
                            value="Upload"
                        {% endif %}

                    /></p>
        </form>
    </div>
</div>
{% include 'mysite/footer.html' %}

mysite/templates/mysite/loginpwd.html
{% include 'mysite/header.html' %}
{% load bootstrap %}
{% load static %}

{% if uid %}
    <div class="container">
        <a href="{% url "mysite:clearlogincookies" %}">用户{{ uid }}您已经登陆，点此退出</a>
    </div>
{% else %}
    <div class="container" align="center">
        <form action="{% url 'mysite:loginpwd' %}" method="post">

                {{form.as_p}}

            </p>
            <p><input type="submit" class="btn btn-default" value="已登记的点此登陆" />&nbsp;<a href="{% url 'mysite:picreg' %}" class="btn btn-default" >没登记的点此注册</a></p>
        </form>
    </div>
{% endif %}

<style type="text/css">
    #navloginpwd {color:red;}
</style>

{% include 'mysite/footer.html' %}

mysite/templates/mysite/manage.html
{% include 'mysite/header.html' %}
{% load static %}
<div class="container">
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse-2">
          <ul class="nav navbar-nav">
            <li> <a href="{% url 'mysite:createpoll' %}" id="navcreatepoll"> 发起投票 </a> </li>
            <li> <a href="{% url 'mysite:reg' %}" id="navreg"> 注册选民 </a> </li>
            <li> <a href="{% url 'mysite:judge' %}" id="navjudge"> 登记审批 </a> </li>
            <li> <a href="{% url 'mysite:regexl' %}" id="navregexl"> 导入选民数据 </a> </li>
            <li> <a href="{% url 'mysite:qryvoters' %}" id="navqryvoters"> 管理选民 </a> </li>
            <li> <a href="{% url 'mysite:addcandidate' %}" id="navaddcandidate"> 添加候选人 </a> </li>
            <li> <a href="{% url 'mysite:qrycandidates' %}" id="navqrycandidates"> 管理候选人 </a> </li>
            <li> <a href="{% url 'mysite:settext' 0%}" id="navedittextorg"> 编辑选举机构 </a> </li>
            <li> <a href="{% url 'mysite:settext' 1%}" id="navedittextpln"> 编辑选举方案 </a> </li>
            <li> <a href="{% url 'mysite:settext' 2%}" id="navedittextpxc"> 编辑法规宣传 </a> </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->


</div>
<style type="text/css">
    #navadmin {color:red;}
</style>

mysite/templates/mysite/poll.html
{% include 'mysite/header.html' %}
{% load static %}

<script>


    optid2 = {{ cnt0 }}

    function addopt2() {
        var tmpinput = document.createElement("input");
        var tmptext = document.createTextNode("CLICK ME");
        var tmpopttopic = document.createTextNode("选项" + optid2 + "：");
        var br = document.createElement("br");
        //tmpinput.appendChild(tmptext);
        tmpinput.id = "wychoice" + optid2;
        tmpinput.name = 'checkbox' + optid2;
        tmpinput.className = "single-checkbox"
        tmpinput.type = "checkbox"

        var tmpinput2 = document.createElement("input");
        tmpinput2.id = "wychoiceval" + optid2;
        tmpinput2.type = "text"
        optid2 += 1;
        var frm = document.getElementById("options2");
        //<input type="checkbox" class="single-checkbox" name="checkbox{{ opt.id }}" value="" /> <input type="text" id = "optionalczvalue"/> <br>
        //frm.appendChild(tmpopttopic);
        frm.appendChild(tmpinput);
        frm.appendChild(tmpinput2);
        frm.appendChild(br);
        document.getElementById("wycnt").value = optid2
    }
    jQuery(function(){
        var limit = 3;
        $('input.single-checkbox').on('change', function(evt) {
           if($(this).siblings(':checked').length >= {{ topic.commitcnt }}) {
               this.checked = false;
           }
        });
        $(document).ready(function(){
            $( "#optionalczvalue" ).keyup( function() {
                $( "#optionalczkey").attr("value",$( "#optionalczvalue" ).val());
            });
        });


    $("#wy").change(function () {
            cnt = 0
            for ( i = 0; i <= optid2; i++) {
                if ($("#wychoice"+ i.toString()).prop('checked')) cnt++;

            }
            if (cnt > {{ topic.commitcnt }}) {
                for ( i = 0; i <= optid2; i++) {
                    $("#wychoice"+ i.toString()).removeAttr('checked');
                }
                alert("委员最多选{{ topic.commitcnt }}个！请重新选择！")
            }
        }
    );


    $("#wy").keyup( function() {
            for ( i = {{ cnt0 }} ; i<=optid2; i++) {
                $("#wychoice"+ i.toString()).attr("value",$( "#wychoiceval"+ i.toString() ).val());
            }

        }
    ) ;

    });







    function validate(form) {
        var valid = confirm('投票之后无法修改，请谨慎进行投票！！！！')
        if(!valid) {
            return false;
        }
        else {
            return confirm('这是最后一次警告，点击确定后进行投票操作！！！');
        }
    }

    function getVote(optid) {
      if (window.XMLHttpRequest) {
        // code for IE7+, Firefox, Chrome, Opera, Safari
        xmlhttp=new XMLHttpRequest();
      } else {  // code for IE6, IE5
        xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
      }
      xmlhttp.onreadystatechange=function() {
        if (xmlhttp.readyState==4 && xmlhttp.status==200) {
          document.getElementById("poll").innerHTML=xmlhttp.responseText;
        }
      }
      xmlhttp.open("GET", "/pollvote/{{topic.id}}" + "/" + optid, true);
      xmlhttp.send();
    }
</script>




<div class="container" id="poll">
    <form onsubmit="return validate(this);" class="form-poll" action="{% url 'mysite:pollvote' %}" method="post" enctype="multipart/form-data">
        <h3>{{ topic.text }}</h3>
        <input type="hidden" value="{{ cnt0 }}" id="wycnt" name="wycnt"/>
        <div id="cz">
        选村长(单选)：<br>
        {% for opt in choices %}
            <input type="radio" name="vote" value="{{ opt.text.username }} {{ opt.text.suffix }}" /> {{ opt.text.username }} &nbsp  {{ opt.text.suffix }}<br>
        {% endfor %}
        <input type="radio" name="vote" id="optionalczkey" value="" /> <input type="text" id = "optionalczvalue"/><br>
        <br>
        </div>
        <div id="wy">
            选村长(最多选{{ topic.commitcnt }}个)：<br>
            <div id="options2">
                {% for opt in choices2 %}
                    <input type="checkbox" id="wychoice{{ forloop.counter0 }}" class="single-checkbox" name="checkbox{{ forloop.counter0 }}" value="{{ opt.text.username }} {{ opt.text.suffix }}" /> {{ opt.text.username }} &nbsp  {{ opt.text.suffix }} <br>
                {% endfor %}
            </div>
            <button type="button" class="btn btn-default" onclick="addopt2()"> 添加委员候选人
            </button>

        </div>
        <input type="submit" class="btn btn-default" value="提交" />
    </form>
</div>

mysite/templates/mysite/qrycandidates.html
{% include 'mysite/manage.html' %}
{% load static %}
{% load bootstrap %}
<div class="container">
    <form action="{% url "mysite:qrycandidates" %}" class="form-horizontal" method="post" >
        <div class="input-group">
            <div class="input-group-btn search-panel">
                <select name="qrytype" style="font-size: large;">
                    <option value="name" {% if selected == "name" %} selected="selected" {% endif %}>姓名:</option>
                </select>
                &nbsp;
            </div>
            <input type="text" class="form-control" name="qrykey" placeholder="搜索关键词" id="search_key" value="">
            <span class="input-group-btn">
                <button class="btn btn-info" type="submit">  查询  </button>
            </span>
        </div>
    </form>
</div>
{% include 'mysite/listtemplate.html' %}

<style type="text/css">
    #navqrycandidates {color:red;}
</style>

mysite/templates/mysite/qryvoters.html
{% include 'mysite/manage.html' %}
{% load static %}
{% load bootstrap %}
<div class="container">
    <form action="{% url "mysite:qryvoters" %}" class="form-horizontal" method="post" >
        <div class="input-group">
            <div class="input-group-btn search-panel">
                <select name="qrytype" style="font-size: large;">
                    <option value="idsn" {% if selected == "idsn" %} selected="selected" {% endif %}>身份证:</option>
                    <option value="name" {% if selected == "name" %} selected="selected" {% endif %}>姓名:</option>
                </select>
                &nbsp;
            </div>
            <input type="text" class="form-control" name="qrykey" placeholder="搜索关键词" id="search_key" value="">
            <span class="input-group-btn">
                <button class="btn btn-info" type="submit">  查询  </button>
            </span>
        </div>
    </form>
</div>
{% include 'mysite/listtemplate.html' %}

<style type="text/css">
    #navqryvoters {color:red;}
</style>
{% include 'mysite/footer.html' %}

mysite/templates/mysite/regexl.html
{% include 'mysite/manage.html' %}
{% load static %}
{% load bootstrap %}
<div class="container">
    <form action="{% url 'mysite:regexl' %}" method="post" enctype="multipart/form-data">
        {{form| bootstrap}}
        <p><input type="submit"  value="导入" /></p>
    </form>
</div>

<style type="text/css">
    #navregexl {color:red;}
</style>

mysite/templates/mysite/settext.html
{% include 'mysite/manage.html' %}
{% load static %}
{% load bootstrap %}

<script>
    tinymce.init({
      selector: 'textarea',
      height: 500,
      plugins: [
        'advlist autolink lists link image charmap print preview anchor',
        'searchreplace visualblocks code fullscreen',
        'insertdatetime media table contextmenu paste code'
      ],
      toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
    });
</script>

<div class="container">
    <div class="container">
        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url 'mysite:settext' textid %}" method="post" enctype="multipart/form-data">
                {{form.as_p}}
           <input type="submit" class="btn btn-default" value="修改" />
        </form>
    </div>
</div>
<style type="text/css">
    #{{navlabel}} {color:red;}
</style>

mysite/templates/mysite/voters.html
{% include 'mysite/header.html' %}
{% load static %}
{% include 'mysite/listtemplate.html' %}

<style type="text/css">
    #navvoters {color:red;}
</style>

{% include 'mysite/footer.html' %}